 ##########################################################################################
##### this section defines all the properties needed for an XML to work with PowerRAD.
##### do not confuse these with xml definations for an application.
##### these are purely system related properties

tomcat.home.dir=C://Tomcat8.5//
appl.home.dir=D://Eclipse_Workspace_Practice//LawyersIns//
xml.domainobjects.sourcedir=${appl.home.dir}src//

#xml.basedir=${tomcat.home.dir}webapps//Manage//WEB-INF//classes//XML//
#html.basedir=${tomcat.home.dir}webapps//Manage//


xml.basedir=${appl.home.dir}web//XML//
html.basedir=${appl.home.dir}web

fileupload.tempdirectory=${tomcat.home.dir}webapps//LawyersIns//WEB-INF//classes//tmp
fileupload.uploaddirectory=${tomcat.home.dir}webapps//AccountantUploadFiles//


appl.LawyersIns.email.IMG_PATH=${appl.home.dir}image//
appl.LawyersIns.email.RELATIVE_PATH=${appl.home.dir}
appl.LawyersIns.email.CSS_DIR=${appl.home.dir}css//


xml.versioning.template=${xml.basedir}templates//versioning.xml
xml.versioning.packagename=com.manage.managemetadata.versioning
xml.versioning.resourceobject=com.manage.managemetadata.versioning.VersionResources
xml.versioning.extendsfrom=com.xmlobjectbuilder.ResourceKeysNode
xml.versioning.validate=false

xml.metadata.template=${xml.basedir}templates//metadata.xml
xml.metadata.common=${xml.basedir}common//metadata.xml
xml.metadata.packagename=com.manage.managemetadata.metadata
xml.metadata.resourceobject=com.manage.managemetadata.metadata.MetaDataResources
xml.metadata.extendsfrom=com.xmlobjectbuilder.ResourceKeysNode
xml.metadata.validate=false
xml.metadata.schema=${xml.basedir}schemas//metadata.xsd
#xml.metadata.applname=METAAPP
xml.metadata.applname=ManageWeb


xml.expressions.template=${xml.basedir}templates//expressions.xml
xml.expressions.common=${xml.basedir}common//expressions.xml
xml.expressions.packagename= com.manage.managemetadata.expressions
xml.expressions.resourceobject= com.manage.managemetadata.expressions.ExpressionResources
xml.expressions.extendsfrom=com.xmlobjectbuilder.ResourceKeysNode
xml.expressions.validate=false


xml.functions.template=${xml.basedir}templates//functions.xml
xml.functions.common=${xml.basedir}common//functions.xml
xml.functions.packagename=com.manage.managemetadata.functions
xml.functions.resourceobject=com.manage.managemetadata.functions.FunctionResources
xml.functions.extendsfrom=com.xmlobjectbuilder.ResourceKeysNode
xml.functions.validate=false

xml.messages.template=${xml.basedir}templates//messages.xml
xml.messages.common=${xml.basedir}common//messages.xml
xml.messages.packagename=com.manage.managemetadata.messages
xml.messages.resourceobject=com.manage.managemetadata.messages.MessageResources
xml.messages.extendsfrom=com.xmlobjectbuilder.ResourceKeysNode
xml.messages.validate=false

xml.flow.template=${xml.basedir}templates//flow.xml
xml.flow.packagename=com.generatedobjects.flow
xml.flow.resourceobject=com.generatedobjects.flow.FlowResources
xml.flow.extendsfrom=com.xmlobjectbuilder.RuleBasedNode
xml.flow.validate=false


xml.components.template=${xml.basedir}templates//components.xml
xml.components.common=${xml.basedir}common//components.xml
xml.components.packagename=com.manage.managecomponent.components
xml.components.resourceobject=com.manage.managecomponent.components.ComponentResources
xml.components.extendsfrom=com.xmlobjectbuilder.ResourceKeysNode


xml.processflow.template=${xml.basedir}templates//processflow.xml
xml.processflow.common=${xml.basedir}common//processflow.xml
xml.processflow.packagename=com.manage.managecomponent.processflow
xml.processflow.resourceobject=com.manage.managecomponent.processflow.ProcessFlowResources
xml.processflow.extendsfrom=com.xmlobjectbuilder.ResourceKeysNode

xml.rules.template=${xml.basedir}templates//rules.xml
xml.rules.common=${xml.basedir}common//rules.xml
xml.rules.packagename=com.manage.managebusinessrules.rules
xml.rules.resourceobject=com.manage.managebusinessrules.rules.RulesResources
xml.rules.extendsfrom=com.xmlobjectbuilder.ResourceKeysNode


xml.reports.template=${xml.basedir}templates//reports.xml
xml.reports.common=${xml.basedir}common//reports.xml
xml.reports.packagename=com.manage.managereporting.reports
xml.reports.resourceobject=com.manage.managereporting.reports.ReportResources
xml.reports.extendsfrom=com.xmlobjectbuilder.ResourceKeysNode

xml.graphs.template=${xml.basedir}templates//graphs.xml
xml.graphs.common=${xml.basedir}common//graphs.xml
xml.graphs.packagename=com.manage.managereporting.graphs
xml.graphs.resourceobject=com.manage.managereporting.graphs.GraphResources
xml.graphs.extendsfrom=com.xmlobjectbuilder.ResourceKeysNode

xml.security.template=${xml.basedir}templates//security.xml
xml.security.common=${xml.basedir}common//security.xml
xml.security.packagename=com.manage.managemetadata.security
xml.security.resourceobject=com.manage.managemetadata.security.SecurityResources
xml.security.extendsfrom=com.xmlobjectbuilder.ResourceKeysNode

############################ Properties are common for all PSM projects ##############################
#################And can be override for a perticular projects #######################################
appl.common.packagestructure.Context=com.powerrad.common.Context
appl.common.packagestructure.Constants=com.outline.common.Constants
appl.common.packagestructure.IResourceKeys=com.outline.xml.IResourceKeys
appl.common.packagestructure.ResourceKeys=com.outline.common.ResourceKeys
appl.common.packagestructure.Email=com.components.email.Email
appl.common.packagestructure.MailSenderIn=com.interfaces.MailSenderIn
appl.common.packagestructure.ComponentFactory=com.interfaces.ComponentFactory
appl.common.packagestructure.FlowUtils=com.outline.util.FlowUtils
appl.common.packagestructure.DateUtils=com.outline.util.DateUtils
appl.common.packagestructure.ClassUtils=com.outline.util.ClassUtils
appl.common.packagestructure.ValidationUtils=com.outline.util.ValidationUtils
appl.common.packagestructure.InetLogger=com.outline.common.log.InetLogger
appl.common.packagestructure.SqlResources=com.outline.ormapping.ibatis.SqlResources
appl.common.packagestructure.ApplicationResources=com.yourcompany.struts.ApplicationResources
appl.common.packagestructure.ResultUtils=com.outline.ormapping.util.ResultUtils
appl.common.packagestructure.HibernateUtil=com.outline.ormapping.hibernate.HibernateUtil
appl.common.packagestructure.CacheManager=com.outline.util.cache.CacheManager
appl.common.packagestructure.InetCacheKey=com.outline.util.cache.InetCacheKey
appl.common.packagestructure.ValidationException=com.outline.common.exceptions.ValidationException
appl.common.packagestructure.FormatUtils=com.outline.util.FormatUtils
appl.common.packagestructure.ImageSource=com.powerrad.common.ImageSource
appl.common.packagestructure.DaoException=com.outline.ormapping.exceptions.DaoException
appl.common.packagestructure.HibernateDaoTemplate=com.outline.ormapping.core.HibernateDaoTemplate
appl.common.packagestructure.PK=com.outline.ormapping.core.PK
appl.common.packagestructure.framework=com.outline.framework
appl.common.packagestructure.FormUtils=com.powerrad.util.FormUtils
appl.common.packagestructure.SecurityData=com.powerrad.common.SecurityData
appl.common.packagestructure.SecurityUtil=com.powerrad.common.SecurityUtil
appl.common.packagestructure.PaginationUtils=com.outline.util.PaginationUtils
appl.common.packagestructure.StoredProcedureExecutor=com.powerrad.storedprocedure.StoredProcedureExcecuter
###################################### loading the commonResources #################################
appl.commonResources.functions=${xml.basedir}commonResources//functions.xml
appl.commonResources.rules=${xml.basedir}commonResources//rules.xml

#######################UTILS Configuration#############################################################

ibatis.sqlMapTemplate=${xml.basedir}templates//SqlMapConfig.xml
ibatis.sqlMapConfig.dtd.url=${xml.basedir}dtd//sql-map-config-2.dtd
appl.UTILS.ibatisconfig=${xml.basedir}utils//ibatis//maps//SqlMapConfig.xml


 
#######################AccountantIns###############################################
appl.LawyersIns.ibatisconfig=${xml.basedir}LawyersIns//ibatis//maps//SqlMapConfig.xml
#appl.AccountantIns.ormapping.tool=ibatis
#appl.AccountantIns.db.type=SQLSERVER
#appl.AccountantIns.db.driver=net.sourceforge.jtds.jdbc.Driver
#appl.AccountantIns.db.url=jdbc:jtds:sqlserver://madhu:1433/insuranceappdb

#appl.AccountantIns.db.username=sa
#appl.AccountantIns.db.password=outline@123


appl.LawyersIns.ormapping.tool=ibatis
appl.LawyersIns.db.type=SQLSERVER
appl.LawyersIns.db.version=2005
#appl.AccountantIns.db.driver=com.microsoft.jdbc.sqlserver.SQLServerDriver
#appl.AccountantIns.db.url=jdbc:microsoft:sqlserver://raghurajs:1433;DatabaseName=AccountantInsurancedb

appl.LawyersIns.db.driver=net.sourceforge.jtds.jdbc.Driver
appl.LawyersIns.db.url=jdbc:jtds:sqlserver://q2server:1433/accinsurancedb
appl.LawyersIns.db.username=sa
appl.LawyersIns.db.password=outline
appl.LawyersIns.db.datasource=java:comp/env/jdbc/lawinsurancedb

#appl.LawyersIns.htmlstartpage=indexinsured.html
appl.LawyersIns.htmlstartpage=indexagent.html
 
########################Utils###################################################
appl.UTILS.ormapping.tool=ibatis
appl.UTILS.db.type=SQLSERVER

############# Miscellaneous Configuration ########
appl.error.forward.url=http://localhost:8080/LawyersIns

##############################################
appl.LawyersIns.estimateform.log.dir=C://LawyersLogs//EstimateForm//

  






 